[[entries]]
id = "1540bc19-c285-4bf6-a7e3-b0a065c7690e"
type = "fix"
description = "keep transitive dependencies intact when trimming the build graph"
author = "@NiklasRosenstein"

[[entries]]
id = "140ffe72-b88c-41e9-b690-9bd7e8dd841c"
type = "refactor"
description = "refactor `TaskGraph` class -- instead of managing multiple states in one class, the `TaskGraph` now only represents one state at a time but has a reference to its previous state via `TaskGraph.parent`. Some methods and parameters have been renamed and `Graph.get_task()` was added"
author = "@NiklasRosenstein"

[[entries]]
id = "c8ab9fbb-e4dd-4b9a-adff-e5cc48c3be82"
type = "improvement"
description = "add `-a,--all` option to the `kraken run` command and `kraken query` subcommands (viz already had it but the behaviour was slightly changed; we never show not selected tasks anymore)"
author = "@NiklasRosenstein"
