[[entries]]
id = "6fc22c82-a61d-4c0c-8b22-4eb47bbfd3da"
type = "improvement"
description = "upgrade to `typeapi^1.3.2` (from `^0.2.2`); among support for Python 3.6 this should also no longer cause errors when `X | Y` or `list[T]` syntax is used in classes that are runtime introspected (like `Task` subclasses)"
author = "@NiklasRosenstein"
